language: node_js

node_js:
  - "stable"

branches:
  only:
  - master
  - /^greenkeeper/.*$/

install:
  - rvm install 2.5.4
  - bundle install
  - npm install

script: ./_bin/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
